-- 테마
INSERT INTO "THEME" VALUES(SEQ_THEME_CODE.NEXTVAL, '힐링 투어', '/images/theme/healing.png');
INSERT INTO "THEME" VALUES(SEQ_THEME_CODE.NEXTVAL, 'k-pop 투어', '/images/theme/kpop.png');
INSERT INTO "THEME" VALUES(SEQ_THEME_CODE.NEXTVAL, '궁 투어', '/images/theme/gyeongbokgung.png');
INSERT INTO "THEME" VALUES(SEQ_THEME_CODE.NEXTVAL, '맛집 투어', '/images/theme/food.png');
INSERT INTO "THEME" VALUES(SEQ_THEME_CODE.NEXTVAL, '역사 투어', '/images/theme/history.png');
INSERT INTO "THEME" VALUES(SEQ_THEME_CODE.NEXTVAL, '에코 투어리즘', '/images/theme/eco.png');
INSERT INTO "THEME" VALUES(SEQ_THEME_CODE.NEXTVAL, '한복 체험', '/images/theme/hanbok.png');
INSERT INTO "THEME" VALUES(SEQ_THEME_CODE.NEXTVAL, '전통 시장 투어', '/images/theme/market.png');
INSERT INTO "THEME" VALUES(SEQ_THEME_CODE.NEXTVAL, '스키장 투어', '/images/theme/ski.png');
INSERT INTO "THEME" VALUES(SEQ_THEME_CODE.NEXTVAL, '서핑 투어', '/images/theme/surfing.png');
INSERT INTO "THEME" VALUES(SEQ_THEME_CODE.NEXTVAL, '한옥 투어', '/images/theme/hanok.png');


-- (이름) 샘플 데이터 2개씩 넣어주세요!! 주석 처리 된 거는 나중에 넣어도 됨!! 

----------------------------------------------------------------------------------

-- 회원 (구매자 판매자 공통) 5,6
SELECT USER_NO, USER_EMAIL, USER_PASSWORD, USER_NAME, USER_TEL, PROFILE_IMG, CREATE_DT, USER_TYPE, USER_STATE
FROM "USER";


-- 회원 (가이드)
INSERT INTO "USER"
(USER_NO, USER_EMAIL, USER_PASSWORD, USER_NAME, USER_TEL, PROFILE_IMG, CREATE_DT, USER_TYPE, USER_STATE)
VALUES(SEQ_USER_NO.NEXTVAL, 'guide05@gmail.com', 'pass05!', '차은우', '01082715213', '/static/images/profile/guide05.jpg', DEFAULT, 'G', 'N');

INSERT INTO "GUIDE"
(USER_NO, LANGUAGE_SKILL, ACTIVITY_AREA, CONFIRMATION_NO, SUPER_GUIDE_FL)
VALUES(SEQ_USER_NO.CURRVAL, 'English', '전주', 'A12830873712', 'N');


INSERT INTO "USER"
(USER_NO, USER_EMAIL, USER_PASSWORD, USER_NAME, USER_TEL, PROFILE_IMG, CREATE_DT, USER_TYPE, USER_STATE)
VALUES(SEQ_USER_NO.NEXTVAL, 'guide06@gmail.com', 'pass06!', '김도연', '01012852123', '/static/images/profile/guide06.jpg', DEFAULT, 'G', 'N');

INSERT INTO "GUIDE"
(USER_NO, LANGUAGE_SKILL, ACTIVITY_AREA, CONFIRMATION_NO, SUPER_GUIDE_FL)
VALUES(SEQ_USER_NO.CURRVAL, 'Chinese', '서울', 'A10291931928', 'N');



-- 회원(여행객) 아이디 : tourist01 통일해주기~~  5,6
SELECT USER_NO, PASSPORT_NO, PRIMARY_LANGUAGE, EMERGENCY_CONTACT, FACE_IMG
FROM TOURIST;

INSERT INTO "USER"
(USER_NO, USER_EMAIL, USER_PASSWORD, USER_NAME, USER_TEL, PROFILE_IMG, CREATE_DT, USER_TYPE, USER_STATE)
VALUES(SEQ_USER_NO.NEXTVAL, 'tourist05@gmail.com', 'pass05!', 'JOHN DOE', '070128389128', NULL, DEFAULT, 'T', 'N');


INSERT INTO "TOURIST"
(USER_NO, PASSPORT_NO, PRIMARY_LANGUAGE, EMERGENCY_CONTACT, FACE_IMG)
VALUES(SEQ_USER_NO.CURRVAL, 'M12380942', 'English', NULL, '/images/profile/tourist05.jpg');


INSERT INTO "USER"
(USER_NO, USER_EMAIL, USER_PASSWORD, USER_NAME, USER_TEL, PROFILE_IMG, CREATE_DT, USER_TYPE, USER_STATE)
VALUES(SEQ_USER_NO.NEXTVAL, 'tourist06@gmail.com', 'pass05!', 'TORIYAMA MEI', '070127467721', NULL, DEFAULT, 'T', 'N');


INSERT INTO "TOURIST"
(USER_NO, PASSPORT_NO, PRIMARY_LANGUAGE, EMERGENCY_CONTACT, FACE_IMG)
VALUES(SEQ_USER_NO.CURRVAL, 'M95871282', 'Japanese', NULL, '/images/profile/tourist06.jpg');


----------------------------------------------------------------------------------

-- 자기소개 (판매자)
SELECT USER_NO, BIRTH_YEAR, JOB, PETS, HOBBY, SUB_LANG, ABROAD_EXPERIENCE, MBTI, STRENGTH, FAVORITE_SONG, TMI, MAJOR, DOPAMINE, USELESS_TALENT, CAP_LIST
FROM PR;

INSERT INTO PR
(USER_NO, BIRTH_YEAR, JOB, PETS, HOBBY, SUB_LANG, ABROAD_EXPERIENCE, MBTI, STRENGTH, FAVORITE_SONG, TMI, MAJOR, DOPAMINE, USELESS_TALENT, CAP_LIST)
VALUES(15, 1997, '고등학교 수학 강사', '애교가 넘치고 장난기 많은 사모예드', '요리와 테니스', NULL, '중국과 이집트 프랑스 미국 독일 인도네시아', 'ESFJ', '한번 시작하면 쉽게 포기하지 않습니다', 'Travel - The Hunts', '오페라 하우스에서 춤을 췄습니다', NULL , NULL, '수탉을 완벽하게 모방할 수 있습니다', NULL);

INSERT INTO PR
(USER_NO, BIRTH_YEAR, JOB, PETS, HOBBY, SUB_LANG, ABROAD_EXPERIENCE, MBTI, STRENGTH, FAVORITE_SONG, TMI, MAJOR, DOPAMINE, USELESS_TALENT, CAP_LIST)
VALUES(17, 1999, '학생', '배고플 때만 집사를 찾는 검은 고양이와 함께 살아요', '사진 찍기', '프랑스어, 일본어, 영어', NULL, 'ENFP', '일과 감정을 분리할 줄 알아요', '방백 - 김여명', '최근 관심이 가는 연예인이 생겼어요', '컴퓨터공학과', NULL, NULL, NULL);
-- 다 넣을 필요 없고 4개 이상 넣기~~




-- 관심 지역 (구매자)
SELECT FAVORITE_REGION_NO, REGION_CODE, USER_NO
FROM FAVORITE_REGION;


INSERT INTO FAVORITE_REGION
(FAVORITE_REGION_NO, REGION_CODE, USER_NO)
VALUES(SEQ_FAVORITE_REGION_NO.NEXTVAL, 8, 18);

INSERT INTO FAVORITE_REGION
(FAVORITE_REGION_NO, REGION_CODE, USER_NO)
VALUES(SEQ_FAVORITE_REGION_NO.NEXTVAL, 1, 18);

INSERT INTO FAVORITE_REGION
(FAVORITE_REGION_NO, REGION_CODE, USER_NO)
VALUES(SEQ_FAVORITE_REGION_NO.NEXTVAL, 4, 19);

INSERT INTO FAVORITE_REGION
(FAVORITE_REGION_NO, REGION_CODE, USER_NO)
VALUES(SEQ_FAVORITE_REGION_NO.NEXTVAL, 6, 19);



--------------------------------------------------------------------------------

-- 상품 (4개씩 넣어주세요~~)
SELECT PRODUCT_NO, PRODUCT_NAME, PRODUCT_PACKAGE, PRODUCT_CONTENT, PRODUCT_PRICE, PRODUCT_ADD_PRICE, PRODUCT_MIN_TOURIST, PRODUCT_MAX_TOURIST, USER_NO, REGION_CODE, THEME_CODE, PRODUCT_STATE, CREATE_DT, GUIDE_LANGUAGE, VIEW_COUNT
FROM PRODUCT;

INSERT INTO PRODUCT
(PRODUCT_NO, PRODUCT_NAME, PRODUCT_PACKAGE, PRODUCT_CONTENT, PRODUCT_PRICE, PRODUCT_ADD_PRICE, PRODUCT_MIN_TOURIST, PRODUCT_MAX_TOURIST, USER_NO, REGION_CODE, THEME_CODE, PRODUCT_STATE, CREATE_DT, GUIDE_LANGUAGE, VIEW_COUNT)
VALUES(SEQ_PRODUCT_NO.NEXTVAL, '', 0, '', 0, '', 0, 0, 0, 0, 0, 'N'	, SYSDATE	, '', 0	);


-- 예약
SELECT RESERVATION_NO, PRODUCT_NO, USER_NO, CREATE_DT, RESERVATION_STATE, PAYMENT_METHOD, GUEST_COUNT, RESERVATION_DT
FROM RESERVATION;

INSERT INTO RESERVATION
(RESERVATION_NO, PRODUCT_NO, USER_NO, CREATE_DT, RESERVATION_STATE, PAYMENT_METHOD, GUEST_COUNT, RESERVATION_DT)
VALUES(SEQ_RESERVATION_NO.NEXTVAL, 0, 0, SYSDATE	, 'Y'	, '', 0, '');

-- 리뷰
SELECT REVIEW_NO, USER_NO, REVIEW_MESSAGE, REVIEW_STARS, REVIEW_DEL_FL, PRODUCT_NO, CREATE_DT
FROM REVIEW;

INSERT INTO REVIEW
(REVIEW_NO, USER_NO, REVIEW_MESSAGE, REVIEW_STARS, REVIEW_DEL_FL, PRODUCT_NO, CREATE_DT)
VALUES(SEQ_REVIEW_NO.NEXTVAL, 0, '', 0, 'N'	, 0, SYSDATE	);


-- 관심 상품 (구매자)
SELECT WISHLIST_NO, USER_NO, PRODUCT_NO, WISH_DT
FROM WISHLIST;

INSERT INTO WISHLIST
(WISHLIST_NO, USER_NO, PRODUCT_NO, WISH_DT)
VALUES(SEQ_WISHLIST_NO.NEXTVAL, 0, 0, SYSDATE);


-- 여행 코스
SELECT COURSE_NO, PRODUCT_NO, COURSE_NAME, COURSE_ORDER, LATITUDE, LONGITUDE, BOSS_COURSE_FL
FROM TOUR_COURSE;

INSERT INTO TOUR_COURSE
(COURSE_NO, PRODUCT_NO, COURSE_NAME, COURSE_ORDER, LATITUDE, LONGITUDE, BOSS_COURSE_FL)
VALUES(SEQ_TOURCOURSE_NO.NEXTVAL, 0, '', 0, '', '', 'N'	);

-- 파일 (상품이미지 임의로 해도됨니다~~)
SELECT FILE_NO, PRODUCT_NO, FILE_ORDER, FILE_PATH
FROM "FILE";

INSERT INTO "FILE"
(FILE_NO, PRODUCT_NO, FILE_ORDER, FILE_PATH)
VALUES(SEQ_FILE_NO.NEXTVAL, 0, 0, '');


-- 상품 일정(옵션) (판매자)
SELECT PRODUCT_DT_NO, PRODUCT_NO, PRODUCT_DT
FROM PRODUCT_DT;

INSERT INTO PRODUCT_DT
(PRODUCT_DT_NO, PRODUCT_NO, PRODUCT_DT)
VALUES(SEQ_PRODUCT_DT_NO.NEXTVAL, 0, '');

/*
-- 채팅
SELECT CHAT_NO, READ_OR_NOT, CHAT_MESSAGE, CHAT_SEND_DT, CHATROOM_NO, USER_NO
FROM CHAT;

INSERT INTO CHAT
(CHAT_NO, READ_OR_NOT, CHAT_MESSAGE, CHAT_SEND_DT, CHATROOM_NO, USER_NO)
VALUES(SEQ_CHAT_NO.NEXTVAL, 'N'	, '', SYSDATE	, 0, 0);


-- 채팅룸
SELECT CHATROOM_NO, CREATE_DT, PRODUCT_NO, USER_NO
FROM CHATROOM;

INSERT INTO CHATROOM
(CHATROOM_NO, CREATE_DT, PRODUCT_NO, USER_NO)
VALUES(SEQ_CHATROOM_NO.NEXTVAL, SYSDATE	, 0, 0);
*/

/*
-- 알림 (구매자 판매자 모두)
SELECT NOTIFICATION_NO, RECEIVER_NO, SENDER_NO, NOTIFICATION_CONTENT, CREATE_DT, NOTIFICATION_URL, NOTIFICATION_TYPE
FROM NOTIFICATION;

INSERT INTO NOTIFICATION
(NOTIFICATION_NO, RECEIVER_NO, SENDER_NO, NOTIFICATION_CONTENT, CREATE_DT, NOTIFICATION_URL, NOTIFICATION_TYPE)
VALUES(SEQ_NOTICE_NO.NEXTVAL, 0, 0, '', '', '', '');
*/

/*
-- 1:1 문의 (구매자 판매자 모두)
SELECT QNA_NO, QNA_EMAIL, QNA_TITLE, QNA_CONTENT, QNA_DATE, QNA_DEL_FL, QNA_CHECK_FL, USER_NO, QNA_ANSWER
FROM QNA;

INSERT INTO QNA
(QNA_NO, QNA_EMAIL, QNA_TITLE, QNA_CONTENT, QNA_DATE, QNA_DEL_FL, QNA_CHECK_FL, USER_NO, QNA_ANSWER)
VALUES(SEQ_QNA_NO.NEXTVAL, '', '', '', SYSDATE	, 'N'	, 'N'	, 0, '');

-- 1:1문의 이미지 (구매자 판매자 모두)
SELECT QNA_IMG_NO, QNA_NO, QNA_IMG
FROM QNA_IMG;

INSERT INTO QNA_IMG
(QNA_IMG_NO, QNA_NO, QNA_IMG)
VALUES(SEQ_QNA_IMG_NO.NEXTVAL, 0, '');

-- 이벤트
SELECT EVENT_NO, EVENT_NAME, EVENT_CONTENT, EVENT_END_DT, CREATE_DT, EVENT_IMG
FROM EVENT;

INSERT INTO EVENT
(EVENT_NO, EVENT_NAME, EVENT_CONTENT, EVENT_END_DT, CREATE_DT, EVENT_IMG)
VALUES(SEQ_EVENT_NO.NEXTVAL, '', '', '', '', '');

*/

/*
-- 테마 (이미 끝)
SELECT THEME_CODE, THEME_NAME
FROM THEME;

INSERT INTO THEME
(THEME_CODE, THEME_NAME)
VALUES(SEQ_THEME_CODE.NEXTVAL, '');
*/





