/* 특정 상품 조회 */
SELECT PRODUCT_NO, PRODUCT_NAME, PRODUCT_PACKAGE, PRODUCT_CONTENT, PRODUCT_PRICE,
PRODUCT_ADD_PRICE, PRODUCT_MIN_TOURIST, PRODUCT_MAX_TOURIST, USER_NO,
THEME_CODE, PRODUCT_STATE, CREATE_DT, GUIDE_LANGUAGE, VIEW_COUNT, REGION_NAME, THEME_NAME
FROM "PRODUCT" P
JOIN "THEME" USING(THEME_CODE);


/* 특정 상품 리뷰 목록 조회 */
SELECT REVIEW_NO, R.USER_NO USER_NO, REVIEW_MESSAGE, REVIEW_STARS,
		REVIEW_DEL_FL, PRODUCT_NO, R.CREATE_DT CREATE_DT, PROFILE_IMG, USER_NAME 
FROM "REVIEW" R
JOIN "USER" U ON(R.USER_NO = U.USER_NO)
WHERE U.USER_STATE = 'N'
AND R.PRODUCT_NO = 4;

SELECT * FROM "USER";
SELECT * FROM "GUIDE";

/* 특정 상품 작성자 정보 조회 */
SELECT USER_NAME, PROFILE_IMG, CREATE_DT, LANGUAGE_SKILL, SUPER_GUIDE_FL
FROM "USER"
JOIN "GUIDE" USING(USER_NO)
WHERE USER_NO = 17;



