-- 지영
-- 회원 (공통)
-- 관리
INSERT INTO "USER"
VALUES(SEQ_USER_NO.NEXTVAL, 'manager00@gmail.com', 'pass00', '최한결', '01000000000', '/images/profile', SYSDATE, 'M', 'N');
--공통_가이드
INSERT INTO "USER"
VALUES(SEQ_USER_NO.NEXTVAL, 'guide01@gmail.com', 'pass01', '김삼순', '01011111111', '/images/profile', SYSDATE, 'G', 'N');
INSERT INTO "USER"
VALUES(SEQ_USER_NO.NEXTVAL, 'guide02@gmail.com', 'pass02', '김이순', '01022222222', '/images/profile', SYSDATE, 'G', 'N');
-- 공통_여행객
INSERT INTO "USER"
VALUES(SEQ_USER_NO.NEXTVAL, 'tourist03@gmail.com', 'pass03', '이삼순', '01033334444', '/images/profile', SYSDATE, 'T', 'N');
INSERT INTO "USER"
VALUES(SEQ_USER_NO.NEXTVAL, 'tourist04@gmail.com', 'pass04', '박사순', '01044443333', '/images/profile', SYSDATE, 'T', 'N');
-- 나
INSERT INTO "USER"
VALUES(SEQ_USER_NO.NEXTVAL, 'seojy1259@gmail.com', 'pass1259', '서지영', '01091365599', '/images/profile', SYSDATE, 'T', 'N');
INSERT INTO "USER"
VALUES(SEQ_USER_NO.NEXTVAL, 'jiyeong5599@daum.net', 'jy', '서졍이', '01012345678', '/images/profile', SYSDATE, 'G', 'N');
COMMIT;

-- 여행객 아이디  
INSERT INTO TOURIST
VALUES(4, '12345678910', 'English', '01011112222', '/images/face');
INSERT INTO TOURIST
VALUES(5, '10987654321', 'Spanish', '01022203330', 'images/face');

-- 프로필 이미지 수정
UPDATE "USER" SET PROFILE_IMG = 'images/signUp/manager.png' WHERE USER_EMAIL  = 'manager00@gmail.com';
UPDATE "USER" SET PROFILE_IMG = 'images/signUp/guide01.png' WHERE USER_EMAIL  = 'guide01@gmail.com';
UPDATE "USER" SET PROFILE_IMG = 'images/signUp/guide02.png' WHERE USER_EMAIL  = 'guide02@gmail.com';
UPDATE "USER" SET PROFILE_IMG = 'images/signUp/tourist03.png' WHERE USER_EMAIL  = 'tourist03@gmail.com';
UPDATE "USER" SET PROFILE_IMG = 'images/signUp/tourist04.png' WHERE USER_EMAIL  = 'tourist04@gmail.com';


UPDATE TOURIST
SET COUNTRY_CODE = 'US'
WHERE USER_NO = 4;
UPDATE TOURIST
SET COUNTRY_CODE = 'ES'
WHERE USER_NO = 5;
COMMIT;

-- 나
INSERT INTO TOURIST
VALUES(34, 'k55995599', 'Korean', '01055995599', 'images/face');
-- 가이드 아이디
INSERT INTO GUIDE
VALUES(6, 'English', '대전', 'A99988877763', 'N');
INSERT INTO GUIDE
VALUES(3, 'French', '서울', 'A88337744495', 'Y');
INSERT INTO GUIDE
VALUES(35, 'English', '서울', 'A38398394829', 'Y');

-- PR
INSERT INTO PR
(USER_NO, BIRTH_YEAR, JOB, PETS, HOBBY, SUB_LANG, ABROAD_EXPERIENCE, MBTI, STRENGTH, FAVORITE_SONG, TMI, MAJOR, DOPAMINE, USELESS_TALENT, CAP_LIST)
VALUES(6, 1998, 'college student', NULL, 'watching Netflix', 'I can also speak French and Chinese', NULL, 'INFJ',
NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO PR
VALUES(3, 1988, 'guide', 'cat name is Mimyo', NULL, 'English', 'I lived in France for 3 years', NULL,
'I am confident in making you smile all day', 'BTS-Fire', NULL, NULL, NULL, NULL, NULL);

-- 지역 코드
INSERT INTO REGION VALUES(SEQ_REGION_CODE.NEXTVAL, '서울');
INSERT INTO REGION VALUES(SEQ_REGION_CODE.NEXTVAL, '인천');
INSERT INTO REGION VALUES(SEQ_REGION_CODE.NEXTVAL, '대전');
INSERT INTO REGION VALUES(SEQ_REGION_CODE.NEXTVAL, '대구');
INSERT INTO REGION VALUES(SEQ_REGION_CODE.NEXTVAL, '울산');
INSERT INTO REGION VALUES(SEQ_REGION_CODE.NEXTVAL, '광주');
INSERT INTO REGION VALUES(SEQ_REGION_CODE.NEXTVAL, '부산');
INSERT INTO REGION VALUES(SEQ_REGION_CODE.NEXTVAL, '제주');
INSERT INTO REGION VALUES(SEQ_REGION_CODE.NEXTVAL, '울릉도');
INSERT INTO REGION VALUES(SEQ_REGION_CODE.NEXTVAL, '독도');
INSERT INTO REGION VALUES(SEQ_REGION_CODE.NEXTVAL, '전주');
INSERT INTO REGION VALUES(SEQ_REGION_CODE.NEXTVAL, '경주');
INSERT INTO REGION VALUES(SEQ_REGION_CODE.NEXTVAL, '담양');
INSERT INTO REGION VALUES(SEQ_REGION_CODE.NEXTVAL, '평창');

COMMIT;

-- PRODUCT 4개
--서울 야시장 2
INSERT INTO PRODUCT
VALUES(SEQ_PRODUCT_NO.NEXTVAL, '밤에 즐기는 광장시장 먹거리 투어', 1, '유명한 야시장을 둘러보고 풍부한 역사에 대해 배우며 문화적 발견의 여정을 떠나보세요. 그 후, 제가 개인적으로 가장 좋아하는 장소로 안내해 드리겠습니다. 이곳에서 정통 한국 요리와 음료를 맛보실 수 있습니다.',
100000, NULL, 1, 4, 6, 1, 4, 'N', SYSDATE, 'English', default);
--제주 스냅 4
INSERT INTO PRODUCT
VALUES(SEQ_PRODUCT_NO.NEXTVAL, '제주도 푸른밤 달과 함께 하는 야경 스냅 Jeju Night Snap', 1, 
'바람이 부는날엔 숲속으로,
별이 쏟아지는 날엔 들판으로,
달빛이 부신 날엔 오름으로..
멋진 음악이 함께 한다면 꿈만 같은 제주도의 푸른밤을 만끽 할 수 있을거에요.',
40000, 5000, 2, 4, 6, 8, 1, 'N', SYSDATE, 'English', default);
--서울 메이크업 3
INSERT INTO PRODUCT
VALUES(SEQ_PRODUCT_NO.NEXTVAL, '개인 스튜디오에서 K-뷰티 메이크업 클래스 Time to Glow up', 1, '전 세계 사람들은 한국 여성이 특히 아름다움에 관심이 있다는 것을 잘 알고 있습니다. 맞나요??
K-뷰티 스타일로 한국 메이크업 아티스트와 함께 피부를 멋지고 젊게 만드는 법을 배워보세요.',
120000, NULL, 1, 2, 3, 1, 1, 'N', SYSDATE, 'Japanese', default);
--부산 서핑 5
INSERT INTO PRODUCT
VALUES(SEQ_PRODUCT_NO.NEXTVAL, '서핑의 도시 부산 송정에서 서핑 체험', 1, '예약한 강습 시간까지 송정해변에 위치한 서프로드 서핑샵에 모입니다.
물에 들어가기전 에 서핑에 대한 안전수칙과 영상교육을 받고, 환복 후 전문 코치와 함께 바다에 나가 직접 파도를 타며 서핑을 즐깁니다.',
65000, NULL, 1, 8, 3, 7, 10, 'N', SYSDATE, 'English&Korean', default);

UPDATE PRODUCT SET REGION_NAME = '서울' WHERE PRODUCT_NO = 2;
UPDATE PRODUCT SET REGION_NAME = '제주' WHERE PRODUCT_NO = 4;
UPDATE PRODUCT SET REGION_NAME = '서울' WHERE PRODUCT_NO = 3;
UPDATE PRODUCT SET REGION_NAME = '부산' WHERE PRODUCT_NO = 5;

UPDATE PRODUCT SET TOUR_DURATION = _ WHERE PRODUCT_NO = _;
UPDATE PRODUCT SET TOUR_DURATION = 2 WHERE PRODUCT_NO = 3;
UPDATE PRODUCT SET TOUR_DURATION = 3 WHERE PRODUCT_NO = 4;
UPDATE PRODUCT SET TOUR_DURATION = 2 WHERE PRODUCT_NO = 5;

ROLLBACK;

INSERT INTO "PRODUCT_OPTION" VALUES(SEQ_OPTION_NO.NEXTVAL, '18:00', 4, 2,); -- 광장시장
INSERT INTO "PRODUCT_OPTION" VALUES(SEQ_OPTION_NO.NEXTVAL, '10:00', 2, 3,);
INSERT INTO "PRODUCT_OPTION" VALUES(SEQ_OPTION_NO.NEXTVAL, '12:00', 2, 3,);
INSERT INTO "PRODUCT_OPTION" VALUES(SEQ_OPTION_NO.NEXTVAL, '21:00', 4, 4,);
INSERT INTO "PRODUCT_OPTION" VALUES(SEQ_OPTION_NO.NEXTVAL, '15:00', 8, 5, );

INSERT INTO "PRODUCT_OPTION" VALUES(옵션 번호, 시간, 최대 인원 수, 상품 번호, 상품 날짜 번호);
INSERT INTO PRODUCT_OPTION
VALUES(SEQ_OPTION_NO.NEXTVAL, '옵션=시간대', 상품의 PRODUCT_MAX_TOURIST 컬럼 값, 상품 번호,  PRODUCT_DT 테이블의 번호=날짜,일정);
INSERT INTO "PRODUCT_OPTION" VALUES(SEQ_OPTION_NO.NEXTVAL, '13:00',30, 19, 39(product_dt 시퀀스));
--광장시장
INSERT INTO "PRODUCT_OPTION" VALUES(SEQ_OPTION_NO.NEXTVAL, '18:00',4, 2, 1);
INSERT INTO "PRODUCT_OPTION" VALUES(SEQ_OPTION_NO.NEXTVAL, '18:00',4, 2, 2);
INSERT INTO "PRODUCT_OPTION" VALUES(SEQ_OPTION_NO.NEXTVAL, '18:00',4, 2, 3);
--메이크업
INSERT INTO "PRODUCT_OPTION" VALUES(SEQ_OPTION_NO.NEXTVAL, '10:00',2, 3, 56);
INSERT INTO "PRODUCT_OPTION" VALUES(SEQ_OPTION_NO.NEXTVAL, '10:00',2, 3, 57);
INSERT INTO "PRODUCT_OPTION" VALUES(SEQ_OPTION_NO.NEXTVAL, '10:00',2, 3, 58);
INSERT INTO "PRODUCT_OPTION" VALUES(SEQ_OPTION_NO.NEXTVAL, '10:00',2, 3, 59);
INSERT INTO "PRODUCT_OPTION" VALUES(SEQ_OPTION_NO.NEXTVAL, '12:00',2, 3, 56);
INSERT INTO "PRODUCT_OPTION" VALUES(SEQ_OPTION_NO.NEXTVAL, '12:00',2, 3, 57);
INSERT INTO "PRODUCT_OPTION" VALUES(SEQ_OPTION_NO.NEXTVAL, '12:00',2, 3, 58);
INSERT INTO "PRODUCT_OPTION" VALUES(SEQ_OPTION_NO.NEXTVAL, '12:00',2, 3, 59);
-- 제주도
INSERT INTO "PRODUCT_OPTION" VALUES(SEQ_OPTION_NO.NEXTVAL, '20:00',4, 4, 60);
INSERT INTO "PRODUCT_OPTION" VALUES(SEQ_OPTION_NO.NEXTVAL, '20:00',4, 4, 61);
INSERT INTO "PRODUCT_OPTION" VALUES(SEQ_OPTION_NO.NEXTVAL, '20:00',4, 4, 62);
INSERT INTO "PRODUCT_OPTION" VALUES(SEQ_OPTION_NO.NEXTVAL, '20:00',4, 4, 63);
INSERT INTO "PRODUCT_OPTION" VALUES(SEQ_OPTION_NO.NEXTVAL, '20:00',4, 4, 64);
INSERT INTO "PRODUCT_OPTION" VALUES(SEQ_OPTION_NO.NEXTVAL, '20:00',4, 4, 65);
--부산 서핑
INSERT INTO "PRODUCT_OPTION" VALUES(SEQ_OPTION_NO.NEXTVAL, '09:00',8, 5, 66);
INSERT INTO "PRODUCT_OPTION" VALUES(SEQ_OPTION_NO.NEXTVAL, '09:00',8, 5, 67);
INSERT INTO "PRODUCT_OPTION" VALUES(SEQ_OPTION_NO.NEXTVAL, '09:00',8, 5, 68);
INSERT INTO "PRODUCT_OPTION" VALUES(SEQ_OPTION_NO.NEXTVAL, '09:00',8, 5, 69);
INSERT INTO "PRODUCT_OPTION" VALUES(SEQ_OPTION_NO.NEXTVAL, '09:00',8, 5, 70);
INSERT INTO "PRODUCT_OPTION" VALUES(SEQ_OPTION_NO.NEXTVAL, '09:00',8, 5, 71);
INSERT INTO "PRODUCT_OPTION" VALUES(SEQ_OPTION_NO.NEXTVAL, '11:00',8, 5, 66);
INSERT INTO "PRODUCT_OPTION" VALUES(SEQ_OPTION_NO.NEXTVAL, '11:00',8, 5, 67);
INSERT INTO "PRODUCT_OPTION" VALUES(SEQ_OPTION_NO.NEXTVAL, '11:00',8, 5, 68);
INSERT INTO "PRODUCT_OPTION" VALUES(SEQ_OPTION_NO.NEXTVAL, '11:00',8, 5, 69);
INSERT INTO "PRODUCT_OPTION" VALUES(SEQ_OPTION_NO.NEXTVAL, '11:00',8, 5, 70);
INSERT INTO "PRODUCT_OPTION" VALUES(SEQ_OPTION_NO.NEXTVAL, '11:00',8, 5, 71);



DELETE FROM PRODUCT_OPTION WHERE OPTION_NO = 16;
COMMIT;

-- 상품 일정(옵션) (판매자)
--광장시장먹거리2 투어 옵션 날짜 3개
INSERT INTO PRODUCT_DT
VALUES(SEQ_PRODUCT_DT_NO.NEXTVAL, 2, '2023/06/30');
INSERT INTO PRODUCT_DT
VALUES(SEQ_PRODUCT_DT_NO.NEXTVAL, 2, '2023/07/15');
INSERT INTO PRODUCT_DT VALUES(SEQ_PRODUCT_DT_NO.NEXTVAL, 2, '2023/07/30');
--메이크업 3 여러 날짜 여러 시간
INSERT INTO PRODUCT_DT VALUES(SEQ_PRODUCT_DT_NO.NEXTVAL, 3, '2023/07/21',default);
INSERT INTO PRODUCT_DT VALUES(SEQ_PRODUCT_DT_NO.NEXTVAL, 3, '2023/07/22',default);
INSERT INTO PRODUCT_DT VALUES(SEQ_PRODUCT_DT_NO.NEXTVAL, 3, '2023/07/28',default);
INSERT INTO PRODUCT_DT VALUES(SEQ_PRODUCT_DT_NO.NEXTVAL, 3, '2023/07/29',default);
-- 제주도4
INSERT INTO PRODUCT_DT VALUES(SEQ_PRODUCT_DT_NO.NEXTVAL, 4, '2023/07/25',default);
INSERT INTO PRODUCT_DT VALUES(SEQ_PRODUCT_DT_NO.NEXTVAL, 4, '2023/07/26',default);
INSERT INTO PRODUCT_DT VALUES(SEQ_PRODUCT_DT_NO.NEXTVAL, 4, '2023/07/27',default);
INSERT INTO PRODUCT_DT VALUES(SEQ_PRODUCT_DT_NO.NEXTVAL, 4, '2023/08/01',default);
INSERT INTO PRODUCT_DT VALUES(SEQ_PRODUCT_DT_NO.NEXTVAL, 4, '2023/08/02',default);
INSERT INTO PRODUCT_DT VALUES(SEQ_PRODUCT_DT_NO.NEXTVAL, 4, '2023/08/03',default);
-- 부산 서핑5
INSERT INTO PRODUCT_DT VALUES(SEQ_PRODUCT_DT_NO.NEXTVAL, 5, '2023/07/26',default);
INSERT INTO PRODUCT_DT VALUES(SEQ_PRODUCT_DT_NO.NEXTVAL, 5, '2023/07/28',default);
INSERT INTO PRODUCT_DT VALUES(SEQ_PRODUCT_DT_NO.NEXTVAL, 5, '2023/08/02',default);
INSERT INTO PRODUCT_DT VALUES(SEQ_PRODUCT_DT_NO.NEXTVAL, 5, '2023/08/04',default);
INSERT INTO PRODUCT_DT VALUES(SEQ_PRODUCT_DT_NO.NEXTVAL, 5, '2023/08/09',default);
INSERT INTO PRODUCT_DT VALUES(SEQ_PRODUCT_DT_NO.NEXTVAL, 5, '2023/08/11',default);



COMMIT;

-- 관심 지역 (구매자)
INSERT INTO FAVORITE_REGION
VALUES(SEQ_FAVORITE_REGION_NO.NEXTVAL, 1, 4);
INSERT INTO FAVORITE_REGION
VALUES(SEQ_FAVORITE_REGION_NO.NEXTVAL, 2, 5);
-- 관심 상품 (구매자)
INSERT INTO WISHLIST
VALUES(SEQ_WISHLIST_NO.NEXTVAL, 4, 3, SYSDATE);
INSERT INTO WISHLIST
VALUES(SEQ_WISHLIST_NO.NEXTVAL, 5, 2, SYSDATE);

-- 예약
INSERT INTO RESERVATION
VALUES(SEQ_RESERVATION_NO.NEXTVAL, 2, 4, SYSDATE, 'Y', 'C', 2, 3);
INSERT INTO RESERVATION
VALUES(SEQ_RESERVATION_NO.NEXTVAL, 4, 5, SYSDATE, 'Y', 'P', 3, 2);

COMMIT;

-- 리뷰
INSERT INTO REVIEW
VALUES(SEQ_REVIEW_NO.NEXTVAL, 4, 'Korean market food is insanely delicious. It''s not expensive at all and I''m satisfied completely!!!
', 4.5, 'N'	, 2, SYSDATE);
INSERT INTO REVIEW
VALUES(SEQ_REVIEW_NO.NEXTVAL, 5, 'It was suddenly raining, and when I told my guide ''I want to proceed with the filming'', I was very surprised that they changed the course accordingly.
I have now changed all of my profiles to pictures from that day.', 5, 'N', 4, SYSDATE);

-- 여행 코스
--광장시장
INSERT INTO TOUR_COURSE
VALUES(SEQ_TOURCOURSE_NO.NEXTVAL, 2, '광장시장', 1, 37.5700398, 126.9996036, 'Y');
-- 제주도 
INSERT INTO TOUR_COURSE
VALUES(SEQ_TOURCOURSE_NO.NEXTVAL, 4, '1100 고지', 4, 33.3576194, 126.4630564, 'Y');
INSERT INTO TOUR_COURSE
VALUES(SEQ_TOURCOURSE_NO.NEXTVAL, 4, '천지연 폭포', 3, 33.246944, 126.554417, 'N');
INSERT INTO TOUR_COURSE
VALUES(SEQ_TOURCOURSE_NO.NEXTVAL, 4, '새연교', 2, 33.2372277, 126.5598598, 'N');
INSERT INTO TOUR_COURSE VALUES(SEQ_TOURCOURSE_NO.NEXTVAL, 4, '제지기오름', 1, 33.241926, 126.60974, 'N');	
-- 서울 메이크업
INSERT INTO TOUR_COURSE VALUES(SEQ_TOURCOURSE_NO.NEXTVAL, 3, '위위 아뜰리에', 1, 37.5239666, 127.0405108, 'Y');	
-- 부산 서핑
INSERT INTO TOUR_COURSE VALUES(SEQ_TOURCOURSE_NO.NEXTVAL, 5, '서프홀릭 송정서핑 본점', 1, 35.1798667, 129.2006029, 'Y');


commit;


-- 파일
INSERT INTO "FILE" VALUES(SEQ_FILE_NO.NEXTVAL, 상품 번호, NULL, NULL, 파일 순서, '/images/signup/.png');
--광장시장 2 야시장 
INSERT INTO "FILE" VALUES(SEQ_FILE_NO.NEXTVAL, 2, NULL, NULL, 1, '/images/signUp/tour02_01.png');
INSERT INTO "FILE" VALUES(SEQ_FILE_NO.NEXTVAL, 2, NULL, NULL, 2, '/images/signUp/tour02_02.png');
INSERT INTO "FILE" VALUES(SEQ_FILE_NO.NEXTVAL, 2, NULL, NULL, 3, '/images/signUp/tour02_03.png');
--메이크업 3
INSERT INTO "FILE" VALUES(SEQ_FILE_NO.NEXTVAL, 3, NULL, NULL, 1, '/images/signUp/tour03_01.png');
INSERT INTO "FILE" VALUES(SEQ_FILE_NO.NEXTVAL, 3, NULL, NULL, 2, '/images/signUp/tour03_02.png');
--제주 야경 스냅4
INSERT INTO "FILE" VALUES(SEQ_FILE_NO.NEXTVAL, 4, NULL, NULL, 1, '/images/signUp/tour04_01.png');
INSERT INTO "FILE" VALUES(SEQ_FILE_NO.NEXTVAL, 4, NULL, NULL, 2, '/images/signUp/tour04_02.png');
INSERT INTO "FILE" VALUES(SEQ_FILE_NO.NEXTVAL, 4, NULL, NULL, 2, '/images/signUp/tour04_03.png');
INSERT INTO "FILE" VALUES(SEQ_FILE_NO.NEXTVAL, 4, NULL, NULL, 2, '/images/signUp/tour04_04.png');
INSERT INTO "FILE" VALUES(SEQ_FILE_NO.NEXTVAL, 4, NULL, NULL, 2, '/images/signUp/tour04_05.png');
INSERT INTO "FILE" VALUES(SEQ_FILE_NO.NEXTVAL, 4, NULL, NULL, 2, '/images/signUp/tour04_06.png');
INSERT INTO "FILE" VALUES(SEQ_FILE_NO.NEXTVAL, 4, NULL, NULL, 2, '/images/signUp/tour04_07.png');
INSERT INTO "FILE" VALUES(SEQ_FILE_NO.NEXTVAL, 4, NULL, NULL, 2, '/images/signUp/tour04_08.png');
INSERT INTO "FILE" VALUES(SEQ_FILE_NO.NEXTVAL, 4, NULL, NULL, 2, '/images/signUp/tour04_09.png');
-- 부산 송정 서핑 5
INSERT INTO "FILE" VALUES(SEQ_FILE_NO.NEXTVAL, 4, NULL, NULL, 2, '/images/signUp/tour05_01.png');
INSERT INTO "FILE" VALUES(SEQ_FILE_NO.NEXTVAL, 4, NULL, NULL, 2, '/images/signUp/tour05_02.png');
INSERT INTO "FILE" VALUES(SEQ_FILE_NO.NEXTVAL, 4, NULL, NULL, 2, '/images/signUp/tour05_03.png');
INSERT INTO "FILE" VALUES(SEQ_FILE_NO.NEXTVAL, 4, NULL, NULL, 2, '/images/signUp/tour05_04.png');



INSERT INTO "FILE" VALUES(SEQ_FILE_NO.NEXTVAL, 2, 1, '/images/file');
INSERT INTO "FILE"
VALUES(SEQ_FILE_NO.NEXTVAL, 2, 2, '/images/file');

DELETE FROM "FILE" WHERE FILE_PATH  = '/images/file';


COMMIT;

-- 회원가입 시 이메일 인증번호용 테이블 생성
CREATE TABLE "AUTH_KEY" (
	"AUTH_KEY_NO"	NUMBER		NOT NULL,
	"CODE"	CHAR(6)		NOT NULL,
	"EMAIL"	VARCHAR2(50)		NOT NULL,
	"CREATE_TIME"	DATE		NOT NULL
);

COMMENT ON COLUMN "AUTH_KEY"."AUTH_KEY_NO" IS '인증키 구분 번호(SEQ_AUTH_KEY_NO)';

COMMENT ON COLUMN "AUTH_KEY"."CODE" IS '코드';

COMMENT ON COLUMN "AUTH_KEY"."EMAIL" IS '이메일';

COMMENT ON COLUMN "AUTH_KEY"."CREATE_TIME" IS '인증 코드 생성 시간';

CREATE SEQUENCE SEQ_AUTH_KEY_NO;

COMMIT;



---------------------------------
-- XML용 sql들

-- 로그인
-- user_type : G(가이드)/T(투어리스트)/M(관리자)에 따라 조인해서 불러와야 함

-- 가이드
SELECT * FROM "USER" 
JOIN "GUIDE" USING (USER_NO) 
WHERE USER_STATE = 'N'
AND USER_EMAIL = 'guide01@gmail.com';

SELECT * FROM "USER" 
JOIN "GUIDE" USING ("USER_NO") 
WHERE "USER_STATE" = 'N'
AND "USER_EMAIL" = 'guide01@gmail.com';

-- 투어리스트
SELECT * FROM "USER" 
JOIN "TOURIST" USING (USER_NO)
WHERE USER_STATE = 'N'
AND USER_EMAIL = 'tourist03@gmail.com';

-- 관리자
SELECT * FROM "USER" 
WHERE USER_STATE = 'N'
AND USER_EMAIL = 'manager00@gmail.com';

-- 실패1
SELECT *
FROM (SELECT * FROM "USER" WHERE "USER_EMAIL" = 'guide01@gmail.com')
JOIN
	WHEN "USER_TYPE" = 'G' THEN "GUIDE"
	WHEN "USER_TYPE" = 'T' THEN "TOURIST"
USING ("USER_NO")
WHERE "USER_STATE" = 'N'
;

-- 실패2
 SELECT *
FROM "USER"
LEFT JOIN "GUIDE" ON "USER"."USER_NO" = "GUIDE"."USER_NO" AND "USER"."USER_TYPE" = 'G'
LEFT JOIN "TOURIST" ON "USER"."USER_NO" = "TOURIST"."USER_NO" AND "USER"."USER_TYPE" = 'T'
WHERE "USER"."USER_EMAIL" = 'guide01@google.com'
  AND (
    ("USER"."USER_TYPE" = 'G' AND "GUIDE"."USER_NO" IS NOT NULL)
    OR ("USER"."USER_TYPE" = 'T' AND "TOURIST"."USER_NO" IS NOT NULL)
    OR "USER"."USER_TYPE" = 'M'
  );
 
-- 성공!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
SELECT *
FROM (
    SELECT *
    FROM "USER"
    WHERE "USER_EMAIL" = 'tourist03@gmail.com'
) u
LEFT JOIN "GUIDE" g ON u."USER_NO" = g."USER_NO" AND u."USER_TYPE" = 'G'
LEFT JOIN "TOURIST" t ON u."USER_NO" = t."USER_NO" AND u."USER_TYPE" = 'T'
WHERE u."USER_STATE" = 'N';

SELECT COUNT(*) FROM "USER"
WHERE USER_EMAIL = 'seojy1259@gmail.com'
AND USER_STATE = 'N';

-- 비번 변경
UPDATE "USER" SET "USER_PASSWORD"='pass1' WHERE "USER_EMAIL" = 'guide01@gmail.com';


SELECT "USER_NAME" FROM "USER" WHERE "USER_EMAIL" = 'flqhscjfja73@naver.com';


COMMIT;

-- 인증 번호
INSERT INTO "AUTH_KEY" VALUES(SEQ_AUTH_KEY_NO.NEXTVAL, 'aaa', 'worudeee@naver.com', DEFAULT);
UPDATE "AUTH_KEY" SET CODE = 'qqq', CREATE_TIME = SYSDATE WHERE EMAIL='worudeee@naver.com';

-- 인증 번호 확인
SELECT COUNT(*) FROM "AUTH_KEY" WHERE "EMAIL"='flqhscjfja73@naver.com' AND "CODE"='w1B633';

-- 계정 정보 확인
SELECT "USER_PASSWORD" FROM "USER" WHERE "USER_EMAIL" = 'tourist04@gmail.com' AND "USER_STATE" = 'N';

UPDATE "USER" SET "USER_STATE" = 'N' WHERE "USER_EMAIL" = 'tourist04@gmail.com' ;


