-- 계정 정보 확인
SELECT "USER_PASSWORD" FROM "USER" WHERE "USER_EMAIL" = 'tourist04@gmail.com' AND "USER_STATE" = 'N';

UPDATE "USER" SET "USER_STATE" = 'N' WHERE "USER_EMAIL" = 'tourist04@gmail.com' ;

COMMIT;


--비번들
SELECT "USER_EMAIL", "USER_PASSWORD" FROM "USER";

-- 투어리스트 회원가입(이메일,비번,이름,전화번호,비상연락처,여권번호,주사용언어)
-- 버려 
DECLARE temp_no NUMBER;
BEGIN
  SELECT SEQ_USER_NO.NEXTVAL INTO temp_no FROM DUAL;
  INSERT INTO "USER" VALUES (temp_no, 'test00@gmail.com', 'pass00', 'name', '00001111', NULL, SYSDATE, 'T', 'N');
  INSERT INTO "TOURIST" VALUES (temp_no, 'passport','English','emergency_contact',NULL, 'ko');
END;
--
DELETE FROM "GUIDE" WHERE USER_NO = 46;
DELETE FROM "TOURIST" WHERE USER_NO = 48;
DELETE FROM "USER" WHERE USER_NO = 48;

-- 기존 비번 조회
SELECT COUNT(*) FROM "USER" WHERE USER_NO = 41 AND USER_PASSWORD = '$2a$10$ytXaaIxt6fjphas2GzfXXOcMGb727xQblLfPUialCkzLCpiFYcdbu';

UPDATE "TOURIST" SET EMERGENCY_CONTACT = 'AAA' WHERE USER_NO = 19;
UPDATE "USER" SET USER_STATE = 'N' WHERE USER_NO = 34;
COMMIT;


