-- ****** 투어리스트 / 가이드 프로필 이동 ******

-- 가이드인지 판매자인지 체크 ( userType: 1 == G / 0 == T)
-- 23 / 24 가이드 G
-- 25 / 26 여행객 T
SELECT COUNT(*) 
FROM "USER"
WHERE USER_NO = 25
AND USER_TYPE = 'G'
;

-- 회원 정보 가져오기 (이메일, 이름, 프로필 이미지)
SELECT USER_EMAIL, USER_NAME, PROFILE_IMG
FROM "USER"
WHERE USER_NO = 25
;

-- 프로필 변경
UPDATE "USER"
SET PROFILE_IMG='/images/userProfile/sample25.jpg';
WHERE USER_NO=25
;



-- 구매 내역 조회
SELECT FILE_NO, PRODUCT_NO, FILE_ORDER, FILE_PATH
FROM "FILE";

SELECT RESERVATION_NO, PRODUCT_NO, USER_NO, CREATE_DT, RESERVATION_STATE, PAYMENT_METHOD, GUEST_COUNT, PRODUCT_DT_NO
FROM RESERVATION;

SELECT PRODUCT_NO, FILE_PATH
FROM "FILE"
JOIN RESERVATION USING (PRODUCT_NO)
WHERE USER_NO = 25
AND FILE_ORDER = 1
;

-- 구매 내역 카운트
SELECT COUNT(PRODUCT_NO)
FROM RESERVATION
WHERE USER_NO = 25
;

-- 나의 리뷰 내역 조회
SELECT REVIEW_NO, REVIEW_MESSAGE, REVIEW_STARS REVIEW_STARS_DOUBLE
	  	, TO_CHAR(R.CREATE_DT, 'YYYY/MM/DD') CREATE_DT, PROFILE_IMG, USER_NAME
	   , PRODUCT_NAME, REVIEW_REPLY
FROM "REVIEW" R
JOIN "USER" U ON(R.USER_NO = U.USER_NO)
JOIN "PRODUCT" USING (PRODUCT_NO)
WHERE U.USER_STATE = 'N'
AND U.USER_NO = 25
AND REVIEW_DEL_FL = 'N'
AND REVIEW_REPLY_DEL_FL = 'N'
ORDER BY 1 DESC
;

COMMIT;

ROLLBACK;
-- 리뷰 수 카운트
SELECT COUNT(*)
FROM REVIEW
WHERE USER_NO = 25
AND REVIEW_REPLY_DEL_FL ='N'
;

-- 구매자 프로필 자신이 쓴 리뷰 목록 더보기 (3개씩)
SELECT * FROM(
	SELECT ROW_NUMBER() OVER (ORDER BY REVIEW_NO DESC) AS NUM
			,REVIEW_NO, REVIEW_MESSAGE, REVIEW_STARS REVIEW_STARS_DOUBLE
		  	, TO_CHAR(R.CREATE_DT, 'YYYY/MM/DD') CREATE_DT, PROFILE_IMG, USER_NAME
		   , PRODUCT_NAME, REVIEW_REPLY
	FROM "REVIEW" R
	JOIN "USER" U ON(R.USER_NO = U.USER_NO)
	JOIN "PRODUCT" USING (PRODUCT_NO)
	WHERE U.USER_STATE = 'N'
	AND U.USER_NO = 25
	AND REVIEW_DEL_FL = 'N'
	AND REVIEW_REPLY_DEL_FL = 'N'
	)
	WHERE NUM > 3
	ORDER BY NUM
	;
	
-- 리뷰 안쓴 목록 가져오기 PRODUCT_NO 있어야 insert
SELECT RS.PRODUCT_NO PRODUCT_NO, PRODUCT_NAME
FROM RESERVATION RS
JOIN "PRODUCT" P ON (RS.PRODUCT_NO=P.PRODUCT_NO)
-- JOIN "REVIEW" R ON (R.PRODUCT_NO=P.PRODUCT_NO)
WHERE RS.USER_NO = 25
AND RESERVATION_STATE = 'D'
AND R.REVIEW_MESSAGE IS NULL
ORDER BY 1 DESC
;

SELECT RS.PRODUCT_NO, P.PRODUCT_NAME, 
	(SELECT R.REVIEW_MESSAGE
	FROM REVIEW R
	WHERE R.PRODUCT_NO = RS.PRODUCT_NO)
FROM RESERVATION RS
JOIN "PRODUCT" P ON RS.PRODUCT_NO = P.PRODUCT_NO
LEFT JOIN "REVIEW" R ON P.PRODUCT_NO = R.PRODUCT_NO AND R.REVIEW_MESSAGE IS NULL
WHERE RS.USER_NO = 25
AND RS.RESERVATION_STATE = 'D'
ORDER BY RS.PRODUCT_NO DESC;

SELECT RS.PRODUCT_NO, P.PRODUCT_NAME, 
	(SELECT R.REVIEW_MESSAGE
	FROM REVIEW R
	WHERE R.PRODUCT_NO = RS.PRODUCT_NO) AS REVIEW_MESSAGE_NULL
FROM RESERVATION RS
JOIN "PRODUCT" P ON RS.PRODUCT_NO = P.PRODUCT_NO
LEFT JOIN "REVIEW" R ON P.PRODUCT_NO = R.PRODUCT_NO AND REVIEW_MESSAGE_NULL IS NULL
WHERE RS.USER_NO = 25
AND RS.RESERVATION_STATE = 'D'
ORDER BY RS.PRODUCT_NO DESC;

SELECT RS.PRODUCT_NO, P.PRODUCT_NAME, 
	(SELECT R.REVIEW_MESSAGE
	FROM REVIEW R
	WHERE R.PRODUCT_NO = RS.PRODUCT_NO
	AND RS.USER_NO = 25
	AND R.REVIEW_MESSAGE IS NULL) AS REVIEW_MESSAGE_NULL
FROM RESERVATION RS
JOIN "PRODUCT" P ON RS.PRODUCT_NO = P.PRODUCT_NO
LEFT JOIN "REVIEW" R ON P.PRODUCT_NO = R.PRODUCT_NO 
WHERE RS.USER_NO = 25
AND RS.RESERVATION_STATE = 'D'
ORDER BY 1 DESC
;



