-- ****** 투어리스트 / 가이드 프로필 이동 ******

-- 가이드인지 판매자인지 체크 ( userType: 1 == G / 0 == T)
-- 23 / 24 가이드 G
-- 25 / 26 여행객 T
SELECT COUNT(*) 
FROM "USER"
WHERE USER_NO = 25
AND USER_TYPE = 'G'
;

-- 회원 정보 가져오기 (이메일, 이름, 프로필 이미지)
SELECT USER_EMAIL, USER_NAME, PROFILE_IMG
FROM "USER"
WHERE USER_NO = 25
;

-- 프로필 변경
UPDATE "USER"
SET PROFILE_IMG='/images/userProfile/sample25.jpg';
WHERE USER_NO=25
;



-- 구매 내역 조회
SELECT FILE_NO, PRODUCT_NO, FILE_ORDER, FILE_PATH
FROM "FILE";

SELECT RESERVATION_NO, PRODUCT_NO, USER_NO, CREATE_DT, RESERVATION_STATE, PAYMENT_METHOD, GUEST_COUNT, PRODUCT_DT_NO
FROM RESERVATION;

SELECT PRODUCT_NO, FILE_PATH
FROM "FILE"
JOIN RESERVATION USING (PRODUCT_NO)
WHERE USER_NO = 25
AND FILE_ORDER = 1
;

-- 구매 내역 카운트
SELECT COUNT(PRODUCT_NO)
FROM RESERVATION
WHERE USER_NO = 25
;

-- 나의 리뷰 내역 조회
SELECT REVIEW_NO, REVIEW_MESSAGE, REVIEW_STARS REVIEW_STARS_DOUBLE
	  	, TO_CHAR(R.CREATE_DT, 'YYYY/MM/DD') CREATE_DT, PROFILE_IMG, USER_NAME
	   , PRODUCT_NAME, REVIEW_REPLY, PRODUCT_NO
FROM "REVIEW" R
JOIN "USER" U ON(R.USER_NO = U.USER_NO)
JOIN "PRODUCT" USING (PRODUCT_NO)
WHERE U.USER_STATE = 'N'
AND U.USER_NO = 25
AND REVIEW_DEL_FL = 'N'
AND REVIEW_REPLY_DEL_FL = 'N'
ORDER BY 1 DESC
;

COMMIT;

ROLLBACK;
-- 리뷰 수 카운트
SELECT COUNT(*)
FROM REVIEW
WHERE USER_NO = 25
AND REVIEW_REPLY_DEL_FL ='N'
;

-- 구매자 프로필 자신이 쓴 리뷰 목록 더보기 (3개씩)
SELECT * FROM(
	SELECT ROW_NUMBER() OVER (ORDER BY REVIEW_NO DESC) AS NUM
			,REVIEW_NO, REVIEW_MESSAGE, REVIEW_STARS REVIEW_STARS_DOUBLE
		  	, TO_CHAR(R.CREATE_DT, 'YYYY/MM/DD') CREATE_DT, PROFILE_IMG, USER_NAME
		   , PRODUCT_NAME, REVIEW_REPLY, PRODUCT_NO
	FROM "REVIEW" R
	JOIN "USER" U ON(R.USER_NO = U.USER_NO)
	JOIN "PRODUCT" USING (PRODUCT_NO)
	WHERE U.USER_STATE = 'N'
	AND U.USER_NO = 25
	AND REVIEW_DEL_FL = 'N'
	AND REVIEW_REPLY_DEL_FL = 'N'
	)
	WHERE NUM > 3
	ORDER BY NUM
	;

SELECT R.PRODUCT_NO, R.USER_NO, PRODUCT_DT_NO, PRODUCT_NAME
FROM RESERVATION R
JOIN PRODUCT P ON (R.PRODUCT_NO=P.PRODUCT_NO)
WHERE R.USER_NO = 25;
	
-- 리뷰 안쓴 목록 가져오기
SELECT R.PRODUCT_NO, R.USER_NO, PRODUCT_DT_NO, PRODUCT_NAME, RV.REVIEW_MESSAGE 
FROM RESERVATION R
JOIN PRODUCT P ON (R.PRODUCT_NO=P.PRODUCT_NO)
LEFT JOIN "REVIEW" RV ON (R.PRODUCT_NO = RV.PRODUCT_NO)
WHERE R.USER_NO = 25
AND R.RESERVATION_STATE = 'D'
AND RV.REVIEW_MESSAGE IS NULL 
ORDER BY R.CREATE_DT DESC 
;

SELECT RS.PRODUCT_NO, RS.PRODUCT_NAME, RS.PRODUCT_DT_NO, 
    (SELECT R.REVIEW_MESSAGE
    FROM REVIEW R
    WHERE R.PRODUCT_NO = RS.PRODUCT_NO
    AND R.USER_NO = 25
    AND R.REVIEW_MESSAGE IS NULL) AS REVIEW_MESSAGE
FROM RESERVATION RS
JOIN "PRODUCT" P ON RS.PRODUCT_NO = P.PRODUCT_NO
LEFT JOIN "REVIEW" R ON P.PRODUCT_NO = R.PRODUCT_NO
WHERE RS.USER_NO = 25
AND RS.RESERVATION_STATE = 'D'
AND R.REVIEW_NO IS NULL
ORDER BY RS.PRODUCT_NO DESC
;

-- 리뷰 등록

INSERT INTO REVIEW
(REVIEW_NO, USER_NO, REVIEW_MESSAGE, REVIEW_STARS, REVIEW_DEL_FL, PRODUCT_NO, CREATE_DT)
VALUES(SEQ_REVIEW_NO.NEXTVAL, 25, 'nice bb', 5, 'N'	, 14, SYSDATE);

-- 리뷰 삭제
DELETE FROM REVIEW
WHERE PRODUCT_NO =0
AND USER_NO =25
;

-- 리뷰 수정
UPDATE REVIEW
SET REVIEW_MESSAGE='수정쓰?', REVIEW_STARS=4.5
WHERE PRODUCT_NO= 19
AND USER_NO = 25
;

COMMIT;


-- 예약 조회 
-- 0. 상품 썸네일 : PRODUCT_NO으로 조회 해서 FILE에서 조회 해오기 (완)
-- 1. 생성 예정 : 예약 번호
-- 2. 주문처리 : 예약 테이블 (RESERVATION_STATE)
-- 3. 날짜 : PRODUCT_DT_NO으로 상품 조회 후 PRODUCT_DT 가져오기
-- 4. 상품 이름 : PRODUCT_NO으로 상품 조회 후 PRODUCT_NAME 가져오기
-- 5. 상품 가격 : 추가 예정
SELECT RESERVATION_NO, R.PRODUCT_NO, R.USER_NO, RESERVATION_STATE, R.PRODUCT_DT_NO,
    (SELECT FILE_PATH FROM "FILE" F 
    WHERE F.PRODUCT_NO = R.PRODUCT_NO
    AND F.FILE_ORDER = 1) AS FILE_PATH,
    (SELECT PD.PRODUCT_DT FROM PRODUCT_DT PD
    WHERE PD.PRODUCT_DT_NO = R.PRODUCT_DT_NO) AS PRODUCT_DT,
    (SELECT P.PRODUCT_NAME FROM PRODUCT P
    WHERE P.PRODUCT_NO = R.PRODUCT_NO) AS PRODUCT_NAME
FROM RESERVATION R
WHERE R.USER_NO = 25
ORDER BY R.PRODUCT_NO 
;

SELECT PRODUCT_DT_NO, PRODUCT_NO, PRODUCT_DT, PRODUCT_DT_AVAILABILITY
FROM PRODUCT_DT;

SELECT PRODUCT_NO, PRODUCT_NAME, PRODUCT_PACKAGE, PRODUCT_CONTENT, PRODUCT_PRICE, PRODUCT_ADD_PRICE, PRODUCT_MIN_TOURIST, PRODUCT_MAX_TOURIST, USER_NO, THEME_CODE, PRODUCT_STATE, CREATE_DT, GUIDE_LANGUAGE, VIEW_COUNT, REGION_NAME, TOUR_DURATION
FROM PRODUCT;

SELECT OPTION_NO, OPTION_NAME, OPTION_REST, PRODUCT_NO
FROM PRODUCT_OPTION;

SELECT RESERVATION_NO, PRODUCT_NO, USER_NO, CREATE_DT, RESERVATION_STATE, PAYMENT_METHOD, GUEST_COUNT, PRODUCT_DT_NO, OPTION_NO
FROM RESERVATION;

-- 예약 수 카운트
SELECT COUNT(*)
FROM RESERVATION
WHERE USER_NO = 25
;

